---
title: "Glossary"
output: html_document
fontsize: 11pt
geometry: margin=1in
---

\


**_Registered all-cause deaths:_** All reported deaths that mention COVID-19 in the death certificate (registered COVID-19 deaths), as well as those that mention another condition as cause of death (registered non-COVID-19 deaths) in that week. 

**_Registered COVID-19 deaths:_** All deaths that mention COVID-19 in the death certificate. A doctor can certify the involvement of COVID-19 based on symptoms and clinical findings – a positive test result is not required.

**_Registered non-COVID-19 deaths:_** All reported deaths that do not mention COVID-19 in the death certificate. 

**_Expected deaths:_** An estimate of all-cause deaths that we would have expected in the absence of the COVID-19 pandemic. Expected deaths are forecast with a time series model using data from the week ending on 8/1/2010 to the week ending on 28/2/2020. Because they are a statistical forecast, they are uncertain and surrounded by a prediction interval.

**_Excess deaths:_** An estimate of the number of all-cause deaths that are substantially higher or lower than expected all-cause deaths in a week. Given by the difference between registered and expected all-cause deaths allowing for the uncertainty in that expectation. 

**_Excess non-COVID-19 deaths:_** An estimate of the number of deaths that are not due to COVID-19 that are substantially higher or lower than expected all-cause deaths in a week. Given by subtracting registered COVID-19 deaths from the difference between registered and expected all-cause deaths, also allowing for the uncertainty in that expectation.


Website updated on `r format(Sys.Date(), "%d/%m/%Y")`.

Website by Daniel Anderson, Giovanni Forchini, Katharina Hauck, Alessandra Lochen, Swapnil Mishra


